apiVersion: batch/v1
kind: CronJob
metadata:
  name: stg-go-generate-user-sd_profile
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        spec:
          containers:
          - name: stg-go-generate-user-sd_profile
            image: europe-west1-docker.pkg.dev/weather-436309/stg-go-generate-user-sd_profile/stg-go-generate_user_sd_profile:latest
            env:
            - name: ENV_VAR_FILE
              value: ".env"
            command: ["./generate_user_sd_profile"]
          restartPolicy: OnFailure
